Repository project-momo/momo-fe, pull requests merged in 2022-12, with the labels that each got.

#3 StoryBook 추가 및 기본 Layout 구성 #1
  .storybook/main.js
  .storybook/preview.js
  assets/images/icon_search.png
  assets/images/ixon_lifestyle.png
  components/common/Category.tsx
  components/common/Header.tsx
  components/common/Title.stories.tsx
  components/common/Title.tsx
  next.config.js
  package-lock.json
  package.json
  pages/Main.tsx
  pages/index.tsx
  stories/Button.stories.tsx
  stories/Button.tsx
  stories/Header/Header.stories.tsx
  stories/Header/Header.tsx
  stories/Header/HeaderButton.stories.tsx
  stories/Header/HeaderButton.tsx
  stories/Header/header.module.css
  stories/Header/headerButton.module.css
  stories/Page.stories.tsx
  stories/Page.tsx
  stories/button.module.css
  stories/page.css
  styles/globals.css
  yarn.lock
Labels: FE, 스타일링, 기능

#7 [FE] 레이아웃 수정 및 추가, 라우터 설정
  .babelrc
  .eslintrc.json
  assets/images/icon_lifestyle.png
  assets/images/index.tsx
  components/common/Category.tsx
  components/common/Header.tsx
  package-lock.json
  package.json
  pages/Main.tsx
  pages/Test/index.jsx
  pages/_app.tsx
  pages/index.tsx
  pages/test2.tsx
  styles/globals.css
  styles/style.js
  yarn.lock
Labels: FE

#10 [FE] Main layout 제작 1차 구현완료 / Modal Compo storybook 업로드
  assets/images/icon_all.svg
  assets/images/icon_arrow.svg
  assets/images/icon_close.png
  assets/images/icon_close.svg
  assets/images/icon_edu.svg
  assets/images/icon_hot.svg
  assets/images/icon_lifestyle.svg
  assets/images/icon_media.svg
  assets/images/icon_notice.svg
  assets/images/icon_search.svg
  assets/images/userImg2.svg
  assets/images/userimg.svg
  components/common/Category.tsx
  components/common/Header.tsx
  components/common/Modal/Modal.stories.tsx
  components/common/Modal/Modal.tsx
  components/common/Modal/ModalCompo/ModalBtn.stories.tsx
  components/common/Modal/ModalCompo/ModalBtn.tsx
  components/common/Modal/ModalCompo/MoimModal.tsx
  components/common/Tag.stories.tsx
  components/common/Tag.tsx
  components/main/Card.tsx
  components/main/MainList.tsx
  components/main/MainTags.tsx
  components/main/Rank.tsx
  components/main/RankList.tsx
  components/rightLayout/RightBox.stories.tsx
  components/rightLayout/RightBox.tsx
  components/rightLayout/RightSubTitle.stories.tsx
  components/rightLayout/RightSubTitle.tsx
  pages/index.tsx
  public/images/icon_all.png
  public/images/icon_lifestyle.png
  public/images/icon_search.png
  stories/Header/Header.stories.tsx
  stories/Header/Header.tsx
  stories/Page.stories.tsx
  stories/Page.tsx
  stories/button.module.css
  stories/page.css
  styles/globals.css
  styles/style.js
Labels: FE, 스타일링

#11 [FE] 마이페이지 UI 1차 구현 완료
  assets/images/icon_crown.svg
  assets/images/icon_heart.svg
  assets/images/icon_lifestyle.svg
  assets/images/icon_piggy.svg
  assets/images/icon_user.svg
  components/common/Category.tsx
  components/mypage/Button.tsx
  components/mypage/List.tsx
  components/mypage/MyCategory.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMettings.tsx
  components/mypage/Point.tsx
  components/mypage/PointList.tsx
  components/mypage/Profile.tsx
  components/mypage/mypage.style.js
  package-lock.json
  package.json
  pages/Test/index.jsx
  pages/_app.tsx
  pages/attending/index.jsx
  pages/index.tsx
  pages/meetings/index.jsx
  pages/mypage/index.jsx
  pages/point/index.jsx
  pages/test2.tsx
  styles/globals.css
  styles/style.js
  yarn.lock
Labels: 스타일링, 기능

#13 [FE] 모임 상세 페이지 제작 / 모달 제작
  .eslintrc.json
  .prettierrc.json
  components/common/Category.tsx
  components/common/Header.tsx
  components/common/Input.stories.tsx
  components/common/Modal/Modal.stories.tsx
  components/common/Modal/Modal.tsx
  components/common/Modal/ModalCompo/ApplicationStatus.tsx
  components/common/Modal/ModalCompo/ModalBtn.stories.tsx
  components/common/Modal/ModalCompo/ModalBtn.tsx
  components/common/Modal/ModalCompo/MoimModal.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/common/SubTitle.stories.tsx
  components/common/Tag.stories.tsx
  components/common/Tag.tsx
  components/common/Title.stories.tsx
  components/common/Title.tsx
  components/detail/Detail.tsx
  components/main/Card.tsx
  components/main/MainList.tsx
  components/main/MainTags.tsx
  components/main/Rank.tsx
  components/main/RankList.tsx
  components/mypage/Application.tsx
  components/mypage/Button.tsx
  components/mypage/Modal.tsx
  components/mypage/MyCategory.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMettings.tsx
  components/mypage/Point.tsx
  components/mypage/PointList.tsx
  components/mypage/Profile.tsx
  components/mypage/mypage.style.js
  components/rightLayout/Notice.tsx
  components/rightLayout/RightBox.stories.tsx
  components/rightLayout/RightBox.tsx
  components/rightLayout/RightSubTitle.stories.tsx
  components/rightLayout/RightSubTitle.tsx
  next.config.js
  package-lock.json
  package.json
  pages/Sub.tsx
  pages/_app.tsx
  pages/attending/index.jsx
  pages/content/create.tsx
  pages/index.tsx
  pages/meetings/index.jsx
  pages/mypage/index.jsx
  pages/point/index.jsx
  stories/Button.stories.tsx
  stories/Button.tsx
  stories/Header/HeaderButton.stories.tsx
  stories/Header/HeaderButton.tsx
  styles/globals.css
  styles/style.js
  yarn.lock
Labels: 스타일링, 리팩토링, 기능

#14 [FE] Login 제작 / eslint 해결
  .eslintrc.json
  .gitignore
  assets/images/Ellipse 8.svg
  assets/images/icon_cmment_add.svg
  assets/images/icon_delete.svg
  assets/images/icon_mdify.svg
  assets/images/icon_moin.svg
  assets/images/icon_price.svg
  assets/images/icon_toggle.svg
  atoms/index.ts
  components/common/Button.stories.tsx
  components/common/Button.tsx
  components/common/Header/Header.tsx
  components/common/Header/HeaderButton.stories.tsx
  components/common/Header/HeaderButton.tsx
  components/common/Header/headerButton.module.css
  components/common/Modal/Modal.tsx
  components/common/Modal/ModalCompo/LoginModal.tsx
  components/common/Modal/ModalCompo/ModalBtn.stories.tsx
  components/common/Tag.tsx
  components/common/button.module.css
  components/detail/Detail.tsx
  components/detail/ModalDetail.tsx
  components/detail/QnAList.tsx
  components/detail/Qna.tsx
  components/detail/QnaInput.tsx
  components/main/MainTags.tsx
  components/main/RankList.tsx
  components/rightLayout/Price.tsx
  components/rightLayout/RightBox.stories.tsx
  components/rightLayout/RightBox.tsx
  components/rightLayout/RightSubTitle.stories.tsx
  components/rightLayout/RightSubTitle.tsx
  package-lock.json
  package.json
  pages/Sub.tsx
  pages/Sub/index.tsx
  pages/Sub/sub/index.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/oauth/index.tsx
  pages/oauth/login/index.tsx
  stories/Header/header.module.css
  yarn.lock
Labels: FE, 버그, 기능

#15 [FE] 상태관리 설정, 리팩토링 진행
  atoms/atom.ts
  atoms/mypage/atoms.ts
  atoms/mypage/selector.tsx
  components/common/Header/Header.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/common/Tag.tsx
  components/mypage/Application.tsx
  components/mypage/Button.tsx
  components/mypage/Modal.tsx
  components/mypage/MyCategory.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMettings.tsx
  components/mypage/MyMettings_attending.tsx
  components/mypage/MyMettings_host.tsx
  components/mypage/MyMettings_mypage.tsx
  components/mypage/Point.tsx
  components/mypage/PointList.tsx
  components/mypage/Profile.tsx
  components/mypage/mypage.style.js
  dummy/mypage/dummy.ts
  package-lock.json
  package.json
  pages/attending/index.jsx
  pages/content/index.tsx
  pages/meetings/index.jsx
  pages/mypage/index.jsx
  pages/point/index.jsx
  yarn.lock
Labels: 버그, 리팩토링, 기능
