Repository project-momo/momo-fe, pull requests merged in 2023-02, with the labels that each got.

#47 [FE] 모임 참여 결제 연동
  components/common/Modal/ModalCompo/AcceptApplication.tsx
  components/common/Modal/ModalCompo/CancelMeeting.tsx
  components/create/Tags.tsx
  components/detail/ModalDetail.tsx
  components/mypage/Application.tsx
  components/mypage/Modal.tsx
  components/mypage/MyMeetingCard.tsx
  pages/mypage/index.tsx
  pages/payment/failed.tsx
  pages/payments/failed.tsx
  pages/payments/success.tsx
  util/token.ts
Labels: 버그, 리팩토링, 기능

#48 [FE] 자신의 글만 수정할 수 있도록 변경
  components/common/Header/Header.tsx
  components/detail/Detail.tsx
  components/detail/ModalDetail.tsx
  components/detail/SubModal.tsx
  pages/oauth/login/index.tsx
  pages/sub/[id].tsx
Labels: FE, 기능

#49 [FE] 인출, 포인트내역 통신 추가
  assets/images/icon_piggy.svg
  components/common/Modal/ModalCompo/CancelMeeting.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/detail/ModalDetail.tsx
  components/main/Rank.tsx
  components/mypage/List.tsx
  components/mypage/Modal.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMeetings_mypage.tsx
  components/mypage/Point.tsx
  components/mypage/PointList.tsx
  components/mypage/Profile.tsx
  dummy/mypage/dummy.ts
  next.config.js
  package-lock.json
  pages/mypage/index.tsx
  pages/point/index.tsx
  yarn.lock
Labels: 버그, 리팩토링, 기능

#51 [FE] 버그 수정
  components/common/Header/Header.tsx
  components/common/Modal/ModalCompo/ApplicationStatus.tsx
  components/common/Modal/ModalCompo/CancelMeeting.tsx
  components/detail/Detail.tsx
  components/detail/QnaInput.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMeetings_attending.tsx
  components/mypage/MyMeetings_mypage.tsx
  components/mypage/Point.tsx
  pages/meeting/update/[id].tsx
  pages/payments/success.tsx
Labels: 버그, 리팩토링, 기능

#56 [FE] 로그인 필요한 수정 사항 제외 수정 완료
  assets/images/icon_ai.svg
  assets/images/icon_design.svg
  assets/images/icon_develop.svg
  assets/images/icon_finance.svg
  assets/images/icon_healthcare.png
  assets/images/icon_social.svg
  components/common/TitleMain.tsx
  components/create/Price.tsx
  components/detail/DatePicker/DatePeriodPicker.tsx
  components/detail/Detail.tsx
  components/detail/ModalDetail.tsx
  components/detail/QnaInput.tsx
  components/main/MainList.tsx
  components/main/MainTags.tsx
  components/main/RankList.tsx
  components/mypage/Button.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/PointList.tsx
  components/rightLayout/Price.tsx
  pages/_app.tsx
  pages/_document.js
  pages/sub/[id].tsx
  util/throttle.ts
Labels: FE, 버그, 기능

#58 [FE] UI 수정
  components/common/Modal/ModalCompo/CancelMeeting.tsx
  components/common/Tag.tsx
  components/main/MainList.tsx
  components/mypage/Application.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/mypage.style.js
  pages/sub/[id].tsx
  util/token.ts
Labels: 스타일링, 기능

#60 [FE] 버그 수정 및 UI 보완
  assets/images/icon_piggy.svg
  atoms/mypage/selector.tsx
  components/common/Category.tsx
  components/common/Header/Header.tsx
  components/common/Modal/ModalCompo/AcceptApplication.tsx
  components/common/Modal/ModalCompo/CancelMeeting.tsx
  components/common/Modal/ModalCompo/CloseMeeting.tsx
  components/common/Modal/ModalCompo/QuickBtn.tsx
  components/common/Modal/ModalCompo/RejectApplication.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/create/Location.tsx
  components/detail/ModalDetail.tsx
  components/detail/QnaInput.tsx
  components/detail/SubModal.tsx
  components/main/MainList.tsx
  components/mypage/List.tsx
  components/mypage/MyCategory.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMeetings_attending.tsx
  components/mypage/Point.tsx
  components/mypage/PointList.tsx
  components/mypage/Profile.tsx
  components/mypage/mypage.style.js
  components/rightLayout/RightSubTitle.tsx
  pages/_app.tsx
  pages/attending/index.tsx
  pages/meeting/create.tsx
  pages/meeting/update/[id].tsx
  pages/meetings/index.tsx
  pages/payments/success.tsx
  pages/sub/[id].tsx
Labels: 스타일링, 버그, 리팩토링

#61 [FE] 버그 수정
  components/common/Modal/ModalCompo/AcceptApplication.tsx
  components/common/Modal/ModalCompo/CancelMeeting.tsx
  components/common/Modal/ModalCompo/CloseMeeting.tsx
  components/common/Modal/ModalCompo/RejectApplication.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/detail/Detail.tsx
  components/detail/ModalDetail.tsx
  components/detail/Qna.tsx
  components/detail/QnaInput.tsx
  components/main/Card.tsx
  components/main/Rank.tsx
  components/mypage/Profile.tsx
  pages/meetings/index.tsx
  pages/payments/success.tsx
  styles/GlobalStyle.ts
Labels: 스타일링, 버그, 리팩토링

#62 [FE] 무한스크롤, 태그 버그 수정
  components/create/Categorys.tsx
  components/create/LiTitle.tsx
  components/create/Location.tsx
  components/create/Tags.tsx
  components/detail/Detail.tsx
  components/detail/ModalDetail.tsx
  components/main/Card.tsx
  components/main/MainList.tsx
  components/main/MainTags.tsx
  components/mypage/List.tsx
  components/mypage/MyMeetings_attending.tsx
  components/mypage/Point.tsx
  components/mypage/PointList.tsx
  components/mypage/Profile.tsx
  pages/attending/index.tsx
  pages/meeting/create.tsx
  util/token.ts
Labels: 스타일링, 버그

#65 [FE] UI 추가 수정
  components/common/Modal/ModalCompo/AcceptApplication.tsx
  components/common/Modal/ModalCompo/CancelMeeting.tsx
  components/common/Modal/ModalCompo/CloseMeeting.tsx
  components/common/Modal/ModalCompo/RejectApplication.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/detail/ModalDetail.tsx
  components/main/Card.tsx
  components/main/MainList.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMeetings_mypage.tsx
  components/mypage/Point.tsx
  components/mypage/Profile.tsx
  components/mypage/mypage.style.js
  pages/attending/index.tsx
  pages/meetings/index.tsx
  pages/payments/success.tsx
Labels: 스타일링, 리팩토링
