Repository project-momo/momo-fe, pull requests merged in 2023-01, with the labels that each got.

#16 [FE] 모임 등록 테스트 완료
  components/common/Header.tsx
  components/create/Categorys.tsx
  components/create/Date/DateRadio.tsx
  components/create/Date/FreeDate.tsx
  components/create/Date/OneDate.tsx
  components/create/Date/PeriodDate.tsx
  components/create/LiTitle.tsx
  components/create/Location.tsx
  components/create/Price.tsx
  components/create/Tags.tsx
  components/create/Time.tsx
  dummy/mypage/dummy.ts
  dummy/mypage/locationDummy.ts
  next.config.js
  package-lock.json
  package.json
  pages/Sub.tsx
  pages/_app.tsx
  pages/content/index.tsx
  pages/meeting/create.tsx
  pages/oauth/login/index.tsx
  styles/globals.css
  styles/style.js
  yarn.lock
Labels: FE, 스타일링, 기능

#19 [FE] 프로필/만든모임/참여모임 테스트완료
  atoms/mypage/atoms.ts
  atoms/mypage/selector.tsx
  components/common/Header/Header.tsx
  components/common/Modal/Modal.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/mypage/Application.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMeetings.tsx
  components/mypage/MyMeetings_attending.tsx
  components/mypage/MyMeetings_mypage.tsx
  components/mypage/MyMettings_host.tsx
  components/mypage/Profile.tsx
  package-lock.json
  pages/attending/index.jsx
  pages/attending/index.tsx
  pages/meetings/index.jsx
  pages/meetings/index.tsx
  pages/mypage/index.jsx
  pages/mypage/index.tsx
  pages/oauth/login/index.tsx
  pages/point/index.tsx
  yarn.lock
Labels: 리팩토링, 기능

#23 [FE] 모임 등록 구현 완료
  components/create/Categorys.tsx
  components/create/Date/DateRadio.tsx
  components/create/Date/FreeDate.tsx
  components/create/Date/OneDate.tsx
  components/create/Date/PeriodDate.tsx
  components/create/LiTitle.tsx
  components/create/Location.tsx
  components/create/Price.tsx
  components/create/Tags.tsx
  components/create/Time.tsx
  dummy/locationDummy.ts
  package-lock.json
  package.json
  pages/content/index.tsx
  pages/meeting/create.tsx
  yarn.lock
Labels: FE, 스타일링, 기능

#25 [FE] 모달 유효성 검사 추가
  .eslintrc.json
  atoms/mypage/atoms.ts
  components/common/Input.tsx
  components/common/Modal/ModalCompo/ApplicationStatus.tsx
  components/common/Modal/ModalCompo/QuickBtn.tsx
  components/common/Modal/ModalCompo/Withdraw.tsx
  components/common/SubTitle.tsx
  components/detail/ModalDetail.tsx
  components/detail/QnAList.tsx
  components/detail/Qna.tsx
  components/detail/QnaInput.tsx
  components/main/Card.tsx
  components/mypage/Application.tsx
  components/mypage/Button.tsx
  components/mypage/List.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMeetings.tsx
  components/mypage/MyMeetings_attending.tsx
  components/mypage/MyMeetings_mypage.tsx
  components/mypage/MyMettings_host.tsx
  components/mypage/Point.tsx
  components/mypage/PointList.tsx
  components/mypage/mypage.style.js
  package-lock.json
  package.json
  pages/Sub/index.tsx
  pages/attending/index.tsx
  pages/meetings/index.tsx
  pages/mypage/index.tsx
  pages/point/index.tsx
  yarn.lock
Labels: 리팩토링, 기능

#26 [FE] Qna 테스트 완료
  .eslintrc.json
  .prettierrc.json
  atoms/mypage/atoms.ts
  atoms/qna/atom.ts
  atoms/qna/selector.tsx
  components/create/Date/FreeDate.tsx
  components/create/Location.tsx
  components/create/Tags.tsx
  components/detail/Detail.tsx
  components/detail/QnAList.tsx
  components/detail/Qna.tsx
  components/detail/QnaInput.tsx
  dummy/create/locationDummy.ts
  pages/meeting/create.tsx
Labels: FE, 스타일링, 기능

#27 [FE] 주소 조회 테스트 완료
  components/create/Location.tsx
  components/detail/Detail.tsx
  components/detail/QnAList.tsx
  components/detail/Qna.tsx
  components/detail/QnaInput.tsx
  dummy/create/locationDummy.ts
  pages/Sub/index.tsx
  pages/meeting/create.tsx
  yarn.lock
Labels: FE, 리팩토링, 기능

#28 [FE] input:number string, 추가주소 옵션 수정
  components/create/Date/DateRadio.tsx
  components/create/LiTitle.tsx
  components/create/Price.tsx
  pages/meeting/create.tsx
Labels: bug, FE

#30 [FE] 버그들 수정
  components/create/Categorys.tsx
  components/create/Date/PeriodDate.tsx
  components/create/Location.tsx
  components/create/Tags.tsx
  pages/meeting/create.tsx
Labels: FE, 버그

#34 [FE] 모달 제작 / 통신테스트
  atoms/mypage/atoms.ts
  atoms/mypage/selector.tsx
  components/common/Header/Header.tsx
  components/common/Modal/ModalCompo/AcceptApplication.tsx
  components/common/Modal/ModalCompo/CloseMeeting.tsx
  components/common/Modal/ModalCompo/RejectApplication.tsx
  components/mypage/Application.tsx
  components/mypage/Button.tsx
  components/mypage/Modal.tsx
  components/mypage/MyMeetingCard.tsx
  components/mypage/MyMeetings_host.tsx
  components/mypage/mypage.style.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/attending/index.tsx
  pages/meetings/index.tsx
  pages/mypage/index.tsx
  pages/payment/failed.tsx
  pages/payment/success.tsx
  tsconfig.json
  yarn.lock
Labels: 버그, 리팩토링, 기능

#36 [FE] 모임 등록 프리뷰 구현
  components/create/Categorys.tsx
  components/create/LiTitle.tsx
  components/create/Location.tsx
  components/create/Time.tsx
  pages/meeting/create.tsx
Labels: FE, 리팩토링

#37 [FE] get Qna 무한 요청 에러 수정
  components/detail/QnAList.tsx
  pages/Sub/[index].tsx
Labels: bug, FE

#38 [FE] 날짜선택 / 시간 선택 추가 및 메인 라우팅수정
  atoms/sub/atom.ts
  components/common/Modal/ModalCompo/ShareModal.tsx
  components/detail/DatePicker/DateFreePicker.tsx
  components/detail/DaySelect.tsx
  components/detail/Detail.tsx
  components/detail/ModalDetail.tsx
  components/detail/TimeList.tsx
  components/main/Card.tsx
  components/main/MainList.tsx
  pages/[category].tsx
  pages/index.tsx
Labels: FE, 리팩토링, 기능

#41 [FE] 메인 카테고리 / 서브페이지 수정 및 남은 작업 공유
  assets/images/kakoLogo.svg
  atoms/atom.ts
  atoms/sub/atom.ts
  components/common/Category.tsx
  components/common/Modal/ModalCompo/LoginModal.tsx
  components/common/Tag.tsx
  components/detail/DatePicker/DateFreePicker.tsx
  components/detail/DatePicker/DatePeriodPicker.tsx
  components/detail/DaySelect.tsx
  components/detail/ModalDetail.tsx
  components/main/Card.tsx
  components/main/MainList.tsx
  pages/Sub/[id].tsx
  pages/[category].tsx
  pages/login/index.tsx
  pages/oauth/index.tsx
Labels: FE, 버그, 기능

#46 [FE] 모임 생성 / 수정 / 삭제 테스트 완료
  atoms/sub/atom.ts
  components/common/Title.tsx
  components/create/Date/PeriodDate.tsx
  components/create/Location.tsx
  components/create/Price.tsx
  components/create/Tags.tsx
  components/detail/SubModal.tsx
  components/mypage/MyMeetingCard.tsx
  pages/meeting/create.tsx
  pages/meeting/update/[id].tsx
Labels: FE, 리팩토링, 기능
